name: Build Docker Images

on:
  pull_request:

jobs:
  build:
    name: Run Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Build Docker Images
        run: npm run docker:build
